Add missing #include<limits> to model_t.cpp
Without this, an error message such as:

    src/model_t.cpp: In member function ‘void cmsh::model_t::config_timeout(double)’:
    src/model_t.cpp:61:59: error: incomplete type ‘std::numeric_limits<double>’ used in nested name specifier
       61 |         solver->set_max_time(std::numeric_limits<double>::max());
          |                                                           ^~~
    src/model_t.cpp: In member function ‘void cmsh::model_t::config_conflicts(int64_t)’:
    src/model_t.cpp:69:61: error: incomplete type ‘std::numeric_limits<long int>’ used in nested name specifier
       69 |         solver->set_max_confl(std::numeric_limits<int64_t>::max());
          |                                                             ^~~
    make: *** [Makefile:69: build/.objects/model_t.o] Error 1

was seen. This is because numeric_limits is defined in limits but it
wasn't included in the necessary source file when includes were changed.

Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>